<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-LogConsumerServer-cb63f8e0-334d-4ead-b3f4-11bcfd6aca45</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Confluent.Kafka" Version="2.14.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.13" />
  </ItemGroup>
</Project>
